apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-read-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /opt/airflow/dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dag-read-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: dag-read-pv
  storageClassName: ""
