apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-read-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /mnt/localfiles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-read-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: text-read-pv
  storageClassName: ""
